#!/bin/bash

host=$1
total=0
loss=0
if [ -z $host ]; then
    echo "Usage: `basename $0` [HOST]"
    exit 1
fi

while :; do
        total=$(( $total + 1 ))
	result=`ping -W 1 -c 1 $host | grep 'bytes from '`
    if [ $? -gt 0 ]; then
        echo -e "$host is \033[0;31mdown\033[0m        Check Your Internet"
	loss=$(( $loss + 1 ))
else
        echo -e "$host is \033[0;32mok\033[0m -`echo $result | cut -d ':' -f 2`";
        sleep 1 # avoid ping rain
fi
echo Loss-Percent
echo -e "( $loss / $total ) * 100" | bc -l |cut -c 1-4
done

